import 'package:habit_tracker/core/utils/app_constants.dart';
import 'package:hive_flutter/hive_flutter.dart';
import '../../features/habits/data/models/habit_model.dart';
import '../../features/tracking/data/models/habit_entry_model.dart';

class HiveSetup {
  /// Initialize Hive database
  static Future<void> initialize() async {
    // Initialize Hive
    await Hive.initFlutter();

    // Register adapters (generated by build_runner)
    Hive.registerAdapter(HabitModelAdapter());
    Hive.registerAdapter(HabitEntryModelAdapter());

    // Open boxes
    await Hive.openBox<HabitModel>(AppConstants.habitsBoxName);
    await Hive.openBox<HabitEntryModel>(AppConstants.entriesBoxName);
  }

  /// Get habits box
  static Box<HabitModel> get habitsBox {
    return Hive.box<HabitModel>(AppConstants.habitsBoxName);
  }

  /// Get entries box
  static Box<HabitEntryModel> get entriesBox {
    return Hive.box<HabitEntryModel>(AppConstants.entriesBoxName);
  }

  /// Close all boxes
  static Future<void> closeAll() async {
    await Hive.close();
  }

  /// Clear all data (for testing or reset)
  static Future<void> clearAll() async {
    await habitsBox.clear();
    await entriesBox.clear();
  }

  /// Get database size
  static Future<Map<String, int>> getDatabaseStats() async {
    return {'habits': habitsBox.length, 'entries': entriesBox.length};
  }

  /// Check if database is initialized
  static bool get isInitialized {
    return Hive.isBoxOpen(AppConstants.habitsBoxName) &&
        Hive.isBoxOpen(AppConstants.entriesBoxName);
  }

  /// Backup data to JSON (for export)
  static Future<Map<String, dynamic>> exportData() async {
    return {
      'habits': habitsBox.values.map((h) => h.toJson()).toList(),
      'entries': entriesBox.values.map((e) => e.toJson()).toList(),
      'exportDate': DateTime.now().toIso8601String(),
    };
  }

  /// Import data from JSON (for import/restore)
  static Future<void> importData(Map<String, dynamic> data) async {
    // Clear existing data
    await clearAll();

    // Import habits
    if (data['habits'] != null) {
      for (final habitJson in data['habits']) {
        final habit = HabitModel.fromJson(habitJson);
        await habitsBox.put(habit.id, habit);
      }
    }

    // Import entries
    if (data['entries'] != null) {
      for (final entryJson in data['entries']) {
        final entry = HabitEntryModel.fromJson(entryJson);
        await entriesBox.put(entry.id, entry);
      }
    }
  }
}
