import 'package:habit_tracker/core/utils/app_constants.dart';
import 'package:habit_tracker/features/profile/data/models/user_profile_model.dart';
import 'package:hive_flutter/hive_flutter.dart';
import '../../features/habits/data/models/habit_model.dart';
import '../../features/tracking/data/models/habit_entry_model.dart';

class HiveSetup {
  /// Initialize Hive database
  static Future<void> initialize() async {
    // Initialize Hive
    await Hive.initFlutter();

    // Register adapters (generated by build_runner)
    Hive.registerAdapter(HabitModelAdapter());
    Hive.registerAdapter(HabitEntryModelAdapter());
    Hive.registerAdapter(UserProfileModelAdapter());

    // Open boxes
    await Hive.openBox<HabitModel>(AppConstants.habitsBoxName);
    await Hive.openBox<HabitEntryModel>(AppConstants.entriesBoxName);
    await Hive.openBox<UserProfileModel>(AppConstants.profileBoxName);
  }

  /// Get habits box
  static Box<HabitModel> get habitsBox {
    return Hive.box<HabitModel>(AppConstants.habitsBoxName);
  }

  /// Get entries box
  static Box<HabitEntryModel> get entriesBox {
    return Hive.box<HabitEntryModel>(AppConstants.entriesBoxName);
  }

  /// Get profile box
  static Box<UserProfileModel> get profileBox {
    return Hive.box<UserProfileModel>(AppConstants.profileBoxName);
  }

  /// Close all boxes
  static Future<void> closeAll() async {
    await Hive.close();
  }

  /// Clear all data (for testing or reset)
  static Future<void> clearAll() async {
    await habitsBox.clear();
    await entriesBox.clear();
    await profileBox.clear();
  }

  /// Get database size
  static Future<Map<String, int>> getDatabaseStats() async {
    return {
      'habits': habitsBox.length,
      'entries': entriesBox.length,
      'hasProfile': profileBox.isNotEmpty ? 1 : 0,
    };
  }

  /// Check if database is initialized
  static bool get isInitialized {
    return Hive.isBoxOpen(AppConstants.habitsBoxName) &&
        Hive.isBoxOpen(AppConstants.entriesBoxName) &&
        Hive.isBoxOpen(AppConstants.profileBoxName);
  }

  /// Backup data to JSON (for export)
  static Future<Map<String, dynamic>> exportData() async {
    return {
      'habits': habitsBox.values.map((h) => h.toJson()).toList(),
      'entries': entriesBox.values.map((e) => e.toJson()).toList(),
      'profile': profileBox.isNotEmpty 
          ? profileBox.getAt(0)?.toJson() 
          : null,
      'exportDate': DateTime.now().toIso8601String(),
    };
  }

  /// Import data from JSON (for import/restore)
  static Future<void> importData(Map<String, dynamic> data) async {
    // Clear existing data
    await clearAll();

    // Import habits
    if (data['habits'] != null) {
      for (final habitJson in data['habits']) {
        final habit = HabitModel.fromJson(habitJson);
        await habitsBox.put(habit.id, habit);
      }
    }

    // Import entries
    if (data['entries'] != null) {
      for (final entryJson in data['entries']) {
        final entry = HabitEntryModel.fromJson(entryJson);
        await entriesBox.put(entry.id, entry);
      }
    }

    // Import profile
    if (data['profile'] != null) {
      final profile = UserProfileModel.fromJson(data['profile']);
      await profileBox.put('user_profile', profile);
    }
  }
}